-- Migration 022: Quotations Table Enhancement for 100% Persistence Sync
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS id VARCHAR(100);
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS quotation_no VARCHAR(100);
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Draft';
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(100);
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS customer_address TEXT;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS items_json JSONB DEFAULT '[]'::jsonb;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(5, 2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS setup_fee NUMERIC(15, 2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS packaging_cost NUMERIC(15, 2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS shipping_fee NUMERIC(15, 2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS expiry_date VARCHAR(50);
