package inventory

import (
	"fmt"
	"log"
	"net/http"
	"sync"
	"time"

	"somsing.local/backend/db"

	"github.com/gin-gonic/gin"
)

// MaintenanceTicket represents a service request ticket triggered by PPM or manual
type MaintenanceTicket struct {
	ID            string     `json:"id"`
	EquipmentID   string     `json:"equipment_id"`
	EquipmentName string     `json:"equipment_name,omitempty"`
	TriggerReason string     `json:"trigger_reason"`
	Status        string     `json:"status"` // "OPEN", "IN_PROGRESS", "RESOLVED"
	ScheduledDate time.Time  `json:"scheduled_date"`
	ResolvedAt    *time.Time `json:"resolved_at,omitempty"`
	CreatedAt     time.Time  `json:"created_at"`
}

// EquipmentHealthIndicator summarizes machine health & PPM status
type EquipmentHealthIndicator struct {
	EquipmentID                    string  `json:"equipment_id"`
	EquipmentName                  string  `json:"equipment_name"`
	CurrentMeter                   int     `json:"current_meter"`
	LastServicedMeter              int     `json:"last_serviced_meter"`
	MaintenanceIntervalImpressions int     `json:"maintenance_interval_impressions"`
	ImpressionsSinceLastService    int     `json:"impressions_since_last_service"`
	HealthPercent                  float64 `json:"health_percent"` // Percentage of interval used (0-100%+)
	HealthStatus                   string  `json:"health_status"`  // "GOOD" (<80%), "SERVICE_DUE_SOON" (80-99%), "REQUIRES_SERVICE" (>=100%)
	ActiveTicketID                 string  `json:"active_ticket_id,omitempty"`
}

var (
	maintenanceTicketsStore = make(map[string]MaintenanceTicket)
	ppmStoreMutex           sync.RWMutex
	ppmTicketSeq            int
)

func init() {
	// Seed demo equipment meters
	ppmStoreMutex.Lock()
	maintenanceTicketsStore["TICKET-PPM-001"] = MaintenanceTicket{
		ID:            "TICKET-PPM-001",
		EquipmentID:   "PRN-OFFSET-01",
		EquipmentName: "Komori Lithrone G40 Offset Press",
		TriggerReason: "Current meter (102,500) exceeded service interval (50,000 imp). Routine roller and blanket overhaul required.",
		Status:        "OPEN",
		ScheduledDate: time.Now().Add(24 * time.Hour),
		CreatedAt:     time.Now().Add(-2 * time.Hour),
	}
	ppmStoreMutex.Unlock()
}

// RunPredictiveMaintenanceCheck evaluates all equipment impressions and generates service tickets
func RunPredictiveMaintenanceCheck() ([]MaintenanceTicket, []EquipmentHealthIndicator) {
	ppmStoreMutex.Lock()
	defer ppmStoreMutex.Unlock()

	var indicators []EquipmentHealthIndicator
	var newTickets []MaintenanceTicket

	// Fetch equipment items
	equipList := getEquipmentSnapshot()

	for _, eq := range equipList {
		currentMeter := 0
		lastServicedMeter := 0
		interval := 50000

		if cm, ok := eq.TechnicalSpecs["current_meter"].(float64); ok && cm > 0 {
			currentMeter = int(cm)
		} else if cmInt, ok := eq.TechnicalSpecs["current_meter"].(int); ok && cmInt > 0 {
			currentMeter = cmInt
		} else {
			currentMeter = 62000 // Sample realistic baseline
		}

		if lsm, ok := eq.TechnicalSpecs["last_serviced_meter"].(float64); ok {
			lastServicedMeter = int(lsm)
		} else if lsmInt, ok := eq.TechnicalSpecs["last_serviced_meter"].(int); ok {
			lastServicedMeter = lsmInt
		}

		if mi, ok := eq.TechnicalSpecs["maintenance_interval_impressions"].(float64); ok && mi > 0 {
			interval = int(mi)
		} else if miInt, ok := eq.TechnicalSpecs["maintenance_interval_impressions"].(int); ok && miInt > 0 {
			interval = miInt
		}

		delta := currentMeter - lastServicedMeter
		if delta < 0 {
			delta = 0
		}

		pct := (float64(delta) / float64(interval)) * 100.0
		healthStatus := "GOOD"
		activeTicketID := ""

		// Check for existing open ticket
		for _, t := range maintenanceTicketsStore {
			if t.EquipmentID == eq.ID && t.Status != "RESOLVED" {
				activeTicketID = t.ID
				break
			}
		}

		if delta >= interval {
			healthStatus = "REQUIRES_SERVICE"
			if activeTicketID == "" {
				ppmTicketSeq++
				ticketID := fmt.Sprintf("TICKET-PPM-%03d", ppmTicketSeq)
				ticket := MaintenanceTicket{
					ID:            ticketID,
					EquipmentID:   eq.ID,
					EquipmentName: eq.Name,
					TriggerReason: fmt.Sprintf("Overdue: Impressions since last service (%d) >= interval (%d). Auto-generated by Predictive Maintenance Cron.", delta, interval),
					Status:        "OPEN",
					ScheduledDate: time.Now().Add(24 * time.Hour),
					CreatedAt:     time.Now(),
				}
				maintenanceTicketsStore[ticketID] = ticket
				newTickets = append(newTickets, ticket)
				activeTicketID = ticketID

				if db.DB != nil {
					_, _ = db.DB.Exec(`
						INSERT INTO maintenance_tickets (id, equipment_id, trigger_reason, status, scheduled_date, created_at)
						VALUES ($1, $2, $3, 'OPEN', NOW() + INTERVAL '1 day', NOW())
						ON CONFLICT (id) DO NOTHING`,
						ticketID, eq.ID, ticket.TriggerReason)
				}
			}
		} else if pct >= 80.0 {
			healthStatus = "SERVICE_DUE_SOON"
		}

		indicators = append(indicators, EquipmentHealthIndicator{
			EquipmentID:                    eq.ID,
			EquipmentName:                  eq.Name,
			CurrentMeter:                   currentMeter,
			LastServicedMeter:              lastServicedMeter,
			MaintenanceIntervalImpressions: interval,
			ImpressionsSinceLastService:    delta,
			HealthPercent:                  pct,
			HealthStatus:                   healthStatus,
			ActiveTicketID:                 activeTicketID,
		})
	}

	return newTickets, indicators
}

func getEquipmentSnapshot() []EquipmentItem {
	storeMutex.RLock()
	defer storeMutex.RUnlock()

	list := make([]EquipmentItem, 0, len(equipmentStore))
	for _, eq := range equipmentStore {
		list = append(list, eq)
	}

	if len(list) == 0 {
		list = []EquipmentItem{
			{
				ID:   "PRN-OFFSET-01",
				Name: "Komori Lithrone G40 Offset Press",
				TechnicalSpecs: map[string]interface{}{
					"current_meter":                    102500,
					"last_serviced_meter":              50000,
					"maintenance_interval_impressions": 50000,
				},
			},
			{
				ID:   "PRN-DIGI-01",
				Name: "Konica Minolta AccurioPress C6085",
				TechnicalSpecs: map[string]interface{}{
					"current_meter":                    42000,
					"last_serviced_meter":              0,
					"maintenance_interval_impressions": 50000,
				},
			},
			{
				ID:   "MACH-LAM-01",
				Name: "Thermal Auto Lamination System 520",
				TechnicalSpecs: map[string]interface{}{
					"current_meter":                    15000,
					"last_serviced_meter":              0,
					"maintenance_interval_impressions": 50000,
				},
			},
		}
	}
	return list
}

// HandleGetEquipmentHealth returns health gauges and meter stats for all machines
func HandleGetEquipmentHealth(c *gin.Context) {
	_, indicators := RunPredictiveMaintenanceCheck()
	c.JSON(http.StatusOK, gin.H{
		"status":     "success",
		"timestamp":  time.Now().Format(time.RFC3339),
		"indicators": indicators,
	})
}

// HandleGetMaintenanceTickets lists open and historical maintenance tickets
func HandleGetMaintenanceTickets(c *gin.Context) {
	ppmStoreMutex.RLock()
	defer ppmStoreMutex.RUnlock()

	list := make([]MaintenanceTicket, 0, len(maintenanceTicketsStore))
	for _, t := range maintenanceTicketsStore {
		list = append(list, t)
	}

	c.JSON(http.StatusOK, gin.H{
		"status":  "success",
		"tickets": list,
	})
}

// HandleTriggerPPMCheck runs an on-demand predictive maintenance inspection
func HandleTriggerPPMCheck(c *gin.Context) {
	newTickets, indicators := RunPredictiveMaintenanceCheck()
	c.JSON(http.StatusOK, gin.H{
		"status":      "success",
		"message":     fmt.Sprintf("PPM Inspection completed. %d new maintenance tickets generated.", len(newTickets)),
		"new_tickets": newTickets,
		"indicators":  indicators,
	})
}

// HandleResolveMaintenanceTicket resolves a ticket and resets the serviced meter
func HandleResolveMaintenanceTicket(c *gin.Context) {
	ticketID := c.Param("id")

	ppmStoreMutex.Lock()
	ticket, exists := maintenanceTicketsStore[ticketID]
	if !exists {
		ppmStoreMutex.Unlock()
		c.JSON(http.StatusNotFound, gin.H{"error": "Maintenance ticket not found"})
		return
	}

	now := time.Now()
	ticket.Status = "RESOLVED"
	ticket.ResolvedAt = &now
	maintenanceTicketsStore[ticketID] = ticket
	ppmStoreMutex.Unlock()

	// Reset equipment last_serviced_meter
	storeMutex.Lock()
	if eq, eqExists := equipmentStore[ticket.EquipmentID]; eqExists {
		if eq.TechnicalSpecs == nil {
			eq.TechnicalSpecs = make(map[string]interface{})
		}
		curMeter := 0
		if cm, ok := eq.TechnicalSpecs["current_meter"].(float64); ok {
			curMeter = int(cm)
		} else if cmInt, ok := eq.TechnicalSpecs["current_meter"].(int); ok {
			curMeter = cmInt
		}
		eq.TechnicalSpecs["last_serviced_meter"] = curMeter
		equipmentStore[ticket.EquipmentID] = eq
	}
	storeMutex.Unlock()

	if db.DB != nil {
		_, _ = db.DB.Exec(`UPDATE maintenance_tickets SET status = 'RESOLVED', resolved_at = NOW() WHERE id = $1`, ticketID)
	}

	c.JSON(http.StatusOK, gin.H{
		"status":  "success",
		"message": "Maintenance ticket resolved and last_serviced_meter reset to current meter",
		"ticket":  ticket,
	})
}

// StartPPMDailyCron runs the predictive maintenance check in the background daily
func StartPPMDailyCron() {
	go func() {
		ticker := time.NewTicker(24 * time.Hour)
		defer ticker.Stop()

		// Run immediate initial check on startup
		log.Println("[PPM CRON] Running startup Predictive Maintenance check...")
		RunPredictiveMaintenanceCheck()

		for range ticker.C {
			log.Println("[PPM CRON] Running scheduled daily Predictive Maintenance check...")
			RunPredictiveMaintenanceCheck()
		}
	}()
}
