import React, { useEffect, useState } from 'react';
import type { ArtworkPart, ArtworkPartCost } from '../types';
import { FileText } from 'lucide-react';
import ArtworkFileActions from './ArtworkFileActions';
import { formatArtworkSize, updateArtworkPart } from '../utils/artworkParts';
import { downloadAuthenticatedFile } from '../../../api/client';
import Lightbox from './Lightbox';

/** Reused selected-file editor or compact order summary; originals stay separate. */
export default function ArtworkPartsPanel({ parts, onChange, papers = [], printers = [], costs = [], compact = !onChange }: { parts: ArtworkPart[]; onChange?: (parts: ArtworkPart[]) => void; papers?: { id: string; name: string }[]; printers?: { id: string; name: string }[]; costs?: ArtworkPartCost[]; compact?: boolean }) {
  const [preview, setPreview] = useState<ArtworkPart | null>(null);
  const sourceKey = parts.map(part => `${part.role}:${part.source.url}:${part.source.name}`).join('|');
  useEffect(() => { setPreview(null); }, [sourceKey]);
  const update = (part: ArtworkPart, patch: Partial<Omit<ArtworkPart, 'role' | 'source' | 'pageCount'>>) => onChange?.(updateArtworkPart(parts, part.role, patch));
  return <div className="space-y-3" data-testid="artwork-parts-panel">
    <div className={`grid gap-3 ${parts.length > 1 ? 'grid-cols-1 lg:grid-cols-2' : 'grid-cols-1'}`}>
      {parts.map(part => <section key={part.role} data-artwork-role={part.role} aria-label={part.role === 'cover' ? 'ໄຟລ໌ປົກ ແລະ ລາຍລະອຽດ' : 'ໄຟລ໌ເນື້ອໃນ ແລະ ລາຍລະອຽດ'} className="p-5 rounded-2xl border border-slate-200 bg-white text-slate-900 space-y-3 shadow-sm">
        <h4 className="font-bold flex items-center gap-2"><FileText aria-hidden="true" className="h-5 w-5 text-sky-600 shrink-0" />{part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'}</h4>
        <p className="break-all text-sm font-semibold" title={part.source.name}>{part.source.name}</p><p className="text-xs text-slate-500">{part.pageCount} ໜ້າ • {formatArtworkSize(part.source.size)}</p>
        {compact ? <div className="text-xs text-slate-600 flex flex-wrap gap-x-4 gap-y-1"><span>{part.paperName || part.paperId || part.paperSize}</span><span>{part.widthMM}×{part.heightMM} mm</span><span>{part.colorMode} • {part.doubleSided ? 'ພິມສອງດ້ານ' : 'ພິມດ້ານດຽວ'}</span><span>C{part.coverage.c} M{part.coverage.m} Y{part.coverage.y} K{part.coverage.k}</span></div> : <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <label>ເຈ້ຍ{onChange ? <select aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ເຈ້ຍ`} value={part.paperId || ''} onChange={e => update(part, { paperId: e.target.value, paperName: papers.find(p => p.id === e.target.value)?.name })} className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400"><option value="">ເລືອກ</option>{part.paperId && !papers.some(p => p.id === part.paperId) && <option value={part.paperId}>{part.paperName || part.paperId}</option>}{papers.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select> : <input aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ເຈ້ຍ`} value={part.paperName || part.paperId || ''} readOnly className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400" />}</label>
          <label>ສີ<select aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ສີ`} value={part.colorMode} disabled={!onChange} onChange={e => update(part, { colorMode: e.target.value })} className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400"><option value="CMYK">CMYK</option><option value="MONO_K">MONO K</option></select></label>
          {(['widthMM', 'heightMM'] as const).map(key => <label key={key}>{key === 'widthMM' ? 'ກວ້າງ (mm)' : 'ສູງ (mm)'}<input aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ${key === 'widthMM' ? 'ກວ້າງ' : 'ສູງ'} mm`} type="number" min="1" value={part[key]} readOnly={!onChange} onChange={e => { const value = Number(e.target.value); if (value > 0) update(part, { [key]: value }); }} className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400" /></label>)}
          {onChange && <label>ເຄື່ອງພິມ<select aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ເຄື່ອງພິມ`} value={part.printerId || ''} onChange={e => update(part, { printerId: e.target.value })} className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400"><option value="">ເລືອກ</option>{part.printerId && !printers.some(p => p.id === part.printerId) && <option value={part.printerId}>{part.printerId}</option>}{printers.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
          {onChange && <label>ຕັດຕໍ່ແຜ່ນ<input aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ຕັດຕໍ່ແຜ່ນ`} type="number" min="1" value={part.cutsPerSheet ?? ''} placeholder="ອັດຕະໂນມັດ" onChange={e => update(part, { cutsPerSheet: e.target.value ? Math.max(1, Number(e.target.value)) : undefined })} className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400" /></label>}
          <label className="col-span-2"><input aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ພິມສອງດ້ານ`} type="checkbox" checked={!!part.doubleSided} disabled={!onChange} onChange={e => update(part, { doubleSided: e.target.checked })} /> ພິມສອງດ້ານ</label>
          {(['c', 'm', 'y', 'k'] as const).map(channel => <label key={channel}>{channel.toUpperCase()} %<input aria-label={`${part.role === 'cover' ? 'ປົກ' : 'ເນື້ອໃນ'} ${channel.toUpperCase()} %`} type="number" min="0" max="100" value={part.coverage[channel]} readOnly={!onChange} onChange={e => { const value = Number(e.target.value); if (value >= 0 && value <= 100) update(part, { coverage: { ...part.coverage, [channel]: value } }); }} className="w-full mt-1 border border-slate-200 rounded-xl px-3 py-2.5 bg-slate-50 text-slate-800 outline-none focus:ring-2 focus:ring-sky-100 focus:border-sky-400" /></label>)}
        </div>}
        {costs.filter(cost => cost.role === part.role).map(cost => <p key={cost.role} className="text-xs" data-testid={`${part.role}-print-cost`}>ຕົ້ນທຶນພິມ: {new Intl.NumberFormat('lo-LA', { maximumFractionDigits: 0 }).format(cost.paperCost + cost.inkCost + cost.machineOverhead)} LAK</p>)}
        <ArtworkFileActions url={part.source.url} name={part.source.name} role={part.role} onPreview={() => setPreview(part)} />
      </section>)}
    </div>
    {preview && parts.some(part => part.role === preview.role && part.source.url === preview.source.url && part.source.name === preview.source.name) && <Lightbox key={preview.source.url} src={preview.source.url} fileName={preview.source.name} fileSize={preview.source.size} contentType={preview.source.mimeType} onDownloadOriginal={() => downloadAuthenticatedFile(preview.source.url, preview.source.name, undefined, preview.source.name).then(() => {})} onClose={() => setPreview(null)} />}
  </div>;
}
