DROP TABLE IF EXISTS accounts_payable CASCADE;
DROP TABLE IF EXISTS expense_records CASCADE;
DROP TABLE IF EXISTS journal_lines CASCADE;
DROP TABLE IF EXISTS journal_entries CASCADE;
DROP TABLE IF EXISTS chart_of_accounts CASCADE;
DROP TYPE IF EXISTS ap_status;
DROP TYPE IF EXISTS account_type;
